install.packages("survey")
library("survey")

# Load the 2019 National Youth Tobacco Survey.
You should reference a particular file including the path or change the working directory. Note this is already an R formatted dataset. You could also open an excel, fixed width, or any other formatted 

load(file ="data/nyts2019.rdata")
attach(nyts2019)

#Problem 1: 
Generate a variable that will be a 1/0 variable, otherwise known as a dummy variable that will be 1 if a student has used ecigarettes in the past 30 days and 0 if they have not used ecigarettes in the past 30 days. Make a decision about how to treat missing. Be careful of the skip pattern (See question 37 and 34 from the codebook).

#Problem 2:
Make up an expected value for the percentage of students that use e-cig?


#Problem 3: 
What is your best estimate of the sample mean of this created variable?


#Problem 4: 
What are possible reasons this measure could be biased?


#Problem 5: 
Take your expectation from problem 2 and write a hypothesis on whether the actual value is the same as your expectation.

#Problem 6: 
Test whether you should reject or not the hypothesis from part 5.

#Problem 7: 
Compute a 95% confidence interval for the estimate from problem 3.






